apiVersion: apps/v1
kind: Deployment
metadata:
  name: viatab
  labels:
    app: viatab   # Update this label value
spec:
  replicas: 2
  selector:
    matchLabels:
      app: viatab   # Update this label value
  template:
    metadata:
      name: viatab
      labels:
        app: viatab   # Update this label value
    spec:
      containers:
        - name: viatab
          image: backend/viatab:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: viatab
  labels:
    app: viatab   # Update this label value
spec:
  selector:
    app: viatab   # Update this label value
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: NodePort
